
[functions.openai-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/openai-proxy/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/openai-proxy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:

[functions.api-produtos]
enabled = true
verify_jwt = false
import_map = "./functions/api-produtos/import_map.json"
entrypoint = "./functions/api-produtos/index.ts"

[functions.api-leads]
enabled = true
verify_jwt = false
import_map = "./functions/api-leads/import_map.json"
entrypoint = "./functions/api-leads/index.ts"
# static_files = [ "./functions/openai-proxy/*.html" ]

[functions.stripe-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-webhook/deno.json"
entrypoint = "./functions/stripe-webhook/index.ts"

[functions.stripe-checkout]
enabled = true
verify_jwt = true
import_map = "./functions/stripe-checkout/deno.json"
entrypoint = "./functions/stripe-checkout/index.ts"

[functions.stripe-portal]
enabled = true
verify_jwt = true
import_map = "./functions/stripe-portal/deno.json"
entrypoint = "./functions/stripe-portal/index.ts"
